{% set name = "pyweed" %}
{% set version = "1.0.8" %}
{% set sha256 = "04dadffba67d04d042c880495346885c2e6c3fc048771b2a911bf3dc19e98ac1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - pyweed = pyweed.pyweed_launcher:launch

requirements:
  host:
    - pip
  run:
    - python
    - basemap <1.5
    - matplotlib-base
    - obspy <1.4
    - pillow
    - pyqt <6
    - pyproj


test:
  imports:
    - pyweed
  commands:
    - python -m pyweed.tests

about:
  home: https://iris-edu.github.io/pyweed/
  dev_url: https://github.com/iris-edu/pyweed
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: "PyWEED: A cross-platform app for retrieving event-based seismic data."

extra:
  recipe-maintainers:
    - adam-iris
